version: '3.4'

services:
    php:
        build:
            args: 
                TIMEZONE: ${TIMEZONE}
            context: .
            dockerfile: ./docker/php/Dockerfile
        tty: true
        working_dir: /var/www
        environment: 
            SERVICE_NAME: php
            SERVICE_TAG: dev
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./logs/beauty_doll:/var/log/beauty_doll:cached
        links: 
            - postgres
        depends_on: 
            - postgres

    maildev:
        image: djfarrelly/maildev
        container_name: sf4_maildev
        ports:
          - 8001:80

    nginx:
        image: nginx:alpine
        tty: true
        ports:
            - "8888:80"
        links:
            - php
        depends_on: 
            - php
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./logs/nginx/:/var/log/nginx:cached

    postgres:
        image: postgres
        ports:
            - "5432:5432"
        working_dir: /var/www
        restart: always
        environment:
            POSTGRES_DB: ${POSTGRES_NAME}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASS}
        volumes:
            - ./database/postgresql/:/var/lib/postgresql/data

    nodejs:
        build:
            context: .
            dockerfile: ./docker/nodejs/Dockerfile
        restart: unless-stopped
        depends_on:
            - php
        ports:
            - "3333:3000"
        volumes:
            - .:/home/app/
            - /home/app/node_modules


#Volumes
volumes:
    postgresql:
        driver: local